"""Sample FAILED files for testing and optimization.

This script copies a random sample of FAILED-*.md files from ParsedFiles/
to a separate directory (ParsedFiles/failed_samples/) that can be committed
to git for testing purposes.

Usage:
    # Sample 10 failed files
    uv run python SimpleWorkflow/sample_fails.py --size 10

    # Sample 30 failed files (good for optimizer testing)
    uv run python SimpleWorkflow/sample_fails.py --size 30

    # Sample all failed files
    uv run python SimpleWorkflow/sample_fails.py --all

    # Clear the samples directory
    uv run python SimpleWorkflow/sample_fails.py --clear

Features:
- Randomly samples FAILED-*.md files
- Preserves file content exactly
- Creates a dedicated directory for samples
- Can be committed to git for reproducible testing
- Useful for sharing failed cases or debugging
"""

# %%
from __future__ import annotations

import argparse
import random
import shutil
import sys
from pathlib import Path


def find_failed_files(source_dir: Path) -> list[Path]:
    """Find all FAILED-*.md files in the source directory.

    Args:
        source_dir: Directory to search for failed files

    Returns:
        List of Path objects for all FAILED-*.md files
    """
    return list(source_dir.glob("FAILED-*.md"))


def sample_failed_files(
    source_dir: Path,
    target_dir: Path,
    sample_size: int,
    all_files: bool = False,
) -> int:
    """Copy a random sample of failed files to target directory.

    Args:
        source_dir: Source directory containing FAILED-*.md files
        target_dir: Destination directory for samples
        sample_size: Number of files to sample
        all_files: If True, copy all failed files

    Returns:
        Number of files copied
    """
    # Find all failed files
    failed_files = find_failed_files(source_dir)

    if not failed_files:
        print("❌ No FAILED-*.md files found in ParsedFiles/")
        return 0

    print(f"📂 Found {len(failed_files)} failed files in ParsedFiles/")

    # Determine sample size
    if all_files:
        sample = failed_files
        print(f"📋 Copying all {len(sample)} failed files...")
    else:
        actual_size = min(sample_size, len(failed_files))
        sample = random.sample(failed_files, actual_size)
        print(f"🎲 Randomly sampling {actual_size} failed files...")

    # Create target directory
    target_dir.mkdir(parents=True, exist_ok=True)

    # Copy files
    copied = 0
    for src_file in sample:
        dst_file = target_dir / src_file.name
        try:
            shutil.copy2(src_file, dst_file)
            copied += 1
            print(f"  ✓ Copied: {src_file.name}")
        except Exception as exc:
            print(f"  ✗ Failed to copy {src_file.name}: {exc}")

    return copied


def clear_samples(target_dir: Path) -> int:
    """Clear all files from the samples directory.

    Args:
        target_dir: Directory to clear

    Returns:
        Number of files removed
    """
    if not target_dir.exists():
        print("📂 Samples directory doesn't exist (nothing to clear)")
        return 0

    files = list(target_dir.glob("FAILED-*.md"))
    if not files:
        print("📂 No failed files in samples directory")
        return 0

    print(f"🗑️  Removing {len(files)} files from samples directory...")
    removed = 0
    for file in files:
        try:
            file.unlink()
            removed += 1
        except Exception as exc:
            print(f"  ✗ Failed to remove {file.name}: {exc}")

    return removed


def create_readme(target_dir: Path) -> None:
    """Create a README in the samples directory.

    Args:
        target_dir: Directory to create README in
    """
    readme_path = target_dir / "README.md"
    readme_content = """# Failed Files Samples

This directory contains sample FAILED-*.md files for testing and debugging.

## Purpose

- **Testing**: Use these samples to test the optimizer without affecting main
  processing
- **Debugging**: Share specific failed cases for troubleshooting
- **Reproducibility**: Commit samples to git for consistent testing across
  machines

## Contents

These files are generated by `sample_fails.py` and represent random samples of
actual PDF parsing failures.

## Usage

### Create New Samples

```bash
# Sample 10 files
uv run python SimpleWorkflow/sample_fails.py --size 10

# Sample 30 files (recommended for optimizer)
uv run python SimpleWorkflow/sample_fails.py --size 30
```

### Clear Samples

```bash
uv run python SimpleWorkflow/sample_fails.py --clear
```

## File Format

Each FAILED-*.md file contains:
- **Frontmatter**: Metadata about the failure (file_identifier, s3_key, error)
- **Traceback**: Full Python traceback of the error

Example:
```
---
file_identifier: 2163984847-ei-document-legislation-file_id_461074
status: FAILED
error: File is not a zip file
s3_key: sea-crawler/2163984847/.../file.pdf
---

# Processing Failed

Traceback (most recent call last):
  ...
```

## Testing with Samples

You can modify the optimizer to test against these samples instead of all
failed files:

```python
# In optimize_retry_workers.py
FAILED_SAMPLES_DIR = Path("SimpleWorkflow/ParsingFailsSamples")
failed_files = find_failed_files(FAILED_SAMPLES_DIR)
```

## Notes

- Files in this directory are committed to git (not in .gitignore)
- Samples are randomly selected each time the script runs
- Original files in ParsedFiles/ are never modified
"""

    readme_path.write_text(readme_content, encoding="utf-8")
    print(f"  ✓ Created README.md in {target_dir}")


def main():
    """Entry point."""
    parser = argparse.ArgumentParser(
        description="Sample FAILED-*.md files for testing and debugging",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Sample 10 failed files
  uv run python SimpleWorkflow/sample_fails.py --size 10

  # Sample 30 failed files (good for optimizer)
  uv run python SimpleWorkflow/sample_fails.py --size 30

  # Copy all failed files
  uv run python SimpleWorkflow/sample_fails.py --all

  # Clear the samples directory
  uv run python SimpleWorkflow/sample_fails.py --clear
        """,
    )

    parser.add_argument(
        "--size",
        type=int,
        default=10,
        help="Number of files to sample (default: 10)",
    )
    parser.add_argument(
        "--all",
        action="store_true",
        help="Copy all failed files instead of sampling",
    )
    parser.add_argument(
        "--clear",
        action="store_true",
        help="Clear all files from samples directory",
    )
    parser.add_argument(
        "--source-dir",
        type=str,
        default="SimpleWorkflow/ParsedFiles",
        help="Source directory (default: SimpleWorkflow/ParsedFiles)",
    )
    parser.add_argument(
        "--target-dir",
        type=str,
        default="SimpleWorkflow/ParsingFailsSamples",
        help=(
            "Target directory for samples "
            "(default: SimpleWorkflow/ParsingFailsSamples)"
        ),
    )

    args = parser.parse_args()

    source_dir = Path(args.source_dir)
    target_dir = Path(args.target_dir)

    print("=" * 70)
    print("FAILED FILES SAMPLER")
    print("=" * 70)
    print()

    if args.clear:
        removed = clear_samples(target_dir)
        print()
        print("=" * 70)
        print(f"✓ Removed {removed} files from samples directory")
        print("=" * 70)
        return 0

    # Validate source directory
    if not source_dir.exists():
        print(f"❌ Source directory does not exist: {source_dir}")
        return 1

    # Sample files
    copied = sample_failed_files(
        source_dir,
        target_dir,
        args.size,
        all_files=args.all,
    )

    # Create README if this is the first time
    readme_path = target_dir / "README.md"
    if not readme_path.exists():
        print()
        create_readme(target_dir)

    # Summary
    print()
    print("=" * 70)
    print(f"✓ Successfully copied {copied} files to {target_dir}")
    print()
    print("📝 You can now:")
    print("   - Commit these samples to git for reproducible testing")
    print("   - Use them for optimizer testing")
    print("   - Share them for debugging specific failures")
    print()
    print("💡 To clear samples later, run:")
    print(f"   uv run python {Path(__file__).name} --clear")
    print("=" * 70)

    return 0


if __name__ == "__main__":
    sys.exit(main())
